# 실제 데이터베이스 드라이버 지정 - mssql
realdriver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 로그 포맷을 CustomP6SpyLogger로 설정
logMessageFormat=com.mobins.common.interceptor.CustomP6SpyLogger

#appender=com.p6spy.engine.spy.appender.Slf4JLogger

## P6Spy 로그 파일 설정 (콘솔 출력과 함께 파일에도 기록)
#logfile=spy.log

# SQL 로그 레벨 설정
#loglevel=debug
#loglevel=info


#statement: 실행된 SQL 쿼리 로그를 출력합니다.
#commit: 트랜잭션 커밋 로그를 기록합니다.
#rollback: 트랜잭션 롤백 로그를 기록합니다.
#result: SQL 실행 결과를 로깅합니다.
#resultset: ResultSet의 데이터를 로깅합니다.
#info: 정보성 메시지를 출력합니다.
#debug: 디버깅 정보를 출력합니다.
#batch: 배치 작업 로그를 기록합니다.
#error: SQL 실행 중 발생한 에러 로그를 기록합니다.

excludecategories=info,debug,result,resultset,commit
includeCategories=statement,rollback,batch,error
#includeBinding=true

## 실행 시간이 1000ms(1초) 이상일 경우 "Slow Query"로 로그 출력
#executionThreshold=1000

## 바인딩된 값 출력
#stringmatcher=true


